# Generated by Django 5.2.2 on 2025-06-26 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='cvv',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='encrypted_card_number',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='last_four_digits',
            field=models.CharField(default='tie', max_length=4),
            preserve_default=False,
        ),
    ]
