# Generated by Django 5.2.2 on 2025-06-10 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('RPG', 'Role-Playing Game'), ('SHOOTER', 'Shooter'), ('SPORTS', 'Sports'), ('RACING', 'Racing'), ('PUZZLE', 'Puzzle'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('FIGHTING', 'Fighting'), ('PLATFORMER', 'Platformer'), ('HORROR', 'Horror'), ('MMO', 'Massively Multiplayer Online'), ('SANDBOX', 'Sandbox'), ('STEALTH', 'Stealth'), ('MUSIC', 'Music/Rhythm'), ('PARTY', 'Party'), ('SURVIVAL', 'Survival'), ('VISUAL_NOVEL', 'Visual Novel'), ('INDIE', 'Indie')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PC', 'PC'), ('MAC', 'Mac'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('XBOX_ONE', 'Xbox One'), ('XBOX_SERIES', 'Xbox Series X/S'), ('SWITCH', 'Nintendo Switch'), ('SWITCH2', 'Nintendo Switch 2')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 10, 23, 39, 5, 824542, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Annapurna', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='Annapurna', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='shopping.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', to='shopping.platform'),
        ),
    ]
