# Generated by Django 5.2.2 on 2025-06-26 01:09

import shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=shopping.models.generate_order_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
