# Generated by Django 5.2.2 on 2025-07-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trailer_url',
        ),
    ]
